//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zleceniodawca.NadzorcaReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Harmonogram", Namespace="http://schemas.datacontract.org/2004/07/WcfNaWzorcach")]
    [System.SerializableAttribute()]
    public partial class Harmonogram : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal kosztCalkowityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Zleceniodawca.NadzorcaReference.Zadanie[] listaZadanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal kosztCalkowity {
            get {
                return this.kosztCalkowityField;
            }
            set {
                if ((this.kosztCalkowityField.Equals(value) != true)) {
                    this.kosztCalkowityField = value;
                    this.RaisePropertyChanged("kosztCalkowity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Zleceniodawca.NadzorcaReference.Zadanie[] listaZadan {
            get {
                return this.listaZadanField;
            }
            set {
                if ((object.ReferenceEquals(this.listaZadanField, value) != true)) {
                    this.listaZadanField = value;
                    this.RaisePropertyChanged("listaZadan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Zadanie", Namespace="http://schemas.datacontract.org/2004/07/WcfNaWzorcach")]
    [System.SerializableAttribute()]
    public partial class Zadanie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Zleceniodawca.NadzorcaReference.Format _formatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Zleceniodawca.NadzorcaReference.Gatunek _gatunekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime _lDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Zleceniodawca.NadzorcaReference.Format _format {
            get {
                return this._formatField;
            }
            set {
                if ((this._formatField.Equals(value) != true)) {
                    this._formatField = value;
                    this.RaisePropertyChanged("_format");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Zleceniodawca.NadzorcaReference.Gatunek _gatunek {
            get {
                return this._gatunekField;
            }
            set {
                if ((this._gatunekField.Equals(value) != true)) {
                    this._gatunekField = value;
                    this.RaisePropertyChanged("_gatunek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime _lD {
            get {
                return this._lDField;
            }
            set {
                if ((this._lDField.Equals(value) != true)) {
                    this._lDField = value;
                    this.RaisePropertyChanged("_lD");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Format", Namespace="http://schemas.datacontract.org/2004/07/WcfNaWzorcach")]
    public enum Format : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Kolo = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Kwadrat = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Prostkoat = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gatunek", Namespace="http://schemas.datacontract.org/2004/07/WcfNaWzorcach")]
    public enum Gatunek : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        S03 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        S200 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        S1000 = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NadzorcaReference.INadzorca")]
    public interface INadzorca {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INadzorca/PobierzLicznik", ReplyAction="http://tempuri.org/INadzorca/PobierzLicznikResponse")]
        int PobierzLicznik();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INadzorca/PobierzLicznik", ReplyAction="http://tempuri.org/INadzorca/PobierzLicznikResponse")]
        System.Threading.Tasks.Task<int> PobierzLicznikAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INadzorca/WstawZlecenie", ReplyAction="http://tempuri.org/INadzorca/WstawZlecenieResponse")]
        void WstawZlecenie(Zleceniodawca.NadzorcaReference.Harmonogram h);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INadzorca/WstawZlecenie", ReplyAction="http://tempuri.org/INadzorca/WstawZlecenieResponse")]
        System.Threading.Tasks.Task WstawZlecenieAsync(Zleceniodawca.NadzorcaReference.Harmonogram h);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INadzorca/PobierzWynik", ReplyAction="http://tempuri.org/INadzorca/PobierzWynikResponse")]
        Zleceniodawca.NadzorcaReference.Harmonogram PobierzWynik();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INadzorca/PobierzWynik", ReplyAction="http://tempuri.org/INadzorca/PobierzWynikResponse")]
        System.Threading.Tasks.Task<Zleceniodawca.NadzorcaReference.Harmonogram> PobierzWynikAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INadzorca/PobierzZlecenie", ReplyAction="http://tempuri.org/INadzorca/PobierzZlecenieResponse")]
        Zleceniodawca.NadzorcaReference.Harmonogram PobierzZlecenie();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INadzorca/PobierzZlecenie", ReplyAction="http://tempuri.org/INadzorca/PobierzZlecenieResponse")]
        System.Threading.Tasks.Task<Zleceniodawca.NadzorcaReference.Harmonogram> PobierzZlecenieAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INadzorca/OddajWynikCzastkowy", ReplyAction="http://tempuri.org/INadzorca/OddajWynikCzastkowyResponse")]
        void OddajWynikCzastkowy(Zleceniodawca.NadzorcaReference.Harmonogram h);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INadzorca/OddajWynikCzastkowy", ReplyAction="http://tempuri.org/INadzorca/OddajWynikCzastkowyResponse")]
        System.Threading.Tasks.Task OddajWynikCzastkowyAsync(Zleceniodawca.NadzorcaReference.Harmonogram h);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INadzorcaChannel : Zleceniodawca.NadzorcaReference.INadzorca, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NadzorcaClient : System.ServiceModel.ClientBase<Zleceniodawca.NadzorcaReference.INadzorca>, Zleceniodawca.NadzorcaReference.INadzorca {
        
        public NadzorcaClient() {
        }
        
        public NadzorcaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NadzorcaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NadzorcaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NadzorcaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int PobierzLicznik() {
            return base.Channel.PobierzLicznik();
        }
        
        public System.Threading.Tasks.Task<int> PobierzLicznikAsync() {
            return base.Channel.PobierzLicznikAsync();
        }
        
        public void WstawZlecenie(Zleceniodawca.NadzorcaReference.Harmonogram h) {
            base.Channel.WstawZlecenie(h);
        }
        
        public System.Threading.Tasks.Task WstawZlecenieAsync(Zleceniodawca.NadzorcaReference.Harmonogram h) {
            return base.Channel.WstawZlecenieAsync(h);
        }
        
        public Zleceniodawca.NadzorcaReference.Harmonogram PobierzWynik() {
            return base.Channel.PobierzWynik();
        }
        
        public System.Threading.Tasks.Task<Zleceniodawca.NadzorcaReference.Harmonogram> PobierzWynikAsync() {
            return base.Channel.PobierzWynikAsync();
        }
        
        public Zleceniodawca.NadzorcaReference.Harmonogram PobierzZlecenie() {
            return base.Channel.PobierzZlecenie();
        }
        
        public System.Threading.Tasks.Task<Zleceniodawca.NadzorcaReference.Harmonogram> PobierzZlecenieAsync() {
            return base.Channel.PobierzZlecenieAsync();
        }
        
        public void OddajWynikCzastkowy(Zleceniodawca.NadzorcaReference.Harmonogram h) {
            base.Channel.OddajWynikCzastkowy(h);
        }
        
        public System.Threading.Tasks.Task OddajWynikCzastkowyAsync(Zleceniodawca.NadzorcaReference.Harmonogram h) {
            return base.Channel.OddajWynikCzastkowyAsync(h);
        }
    }
}
